server:
  port: 8080
  servlet:
    context-path: /adamstore

spring:
  application:
    name: Spring_AdamStore
  profiles:
    active: dev

auth:
  register:
    verification-code:
      expiration-minutes: 5

  forgot-password:
    verification-code:
      expiration-minutes: 10